# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ghost_pb2 as ghost__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ghost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GhostPipelineStub:
    """Ghost IT Agent → Pipeline Server communication
    All connections: mTLS required

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestEvents = channel.stream_unary(
                '/ghost.GhostPipeline/IngestEvents',
                request_serializer=ghost__pb2.EventBatch.SerializeToString,
                response_deserializer=ghost__pb2.IngestResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/ghost.GhostPipeline/HealthCheck',
                request_serializer=ghost__pb2.HealthRequest.SerializeToString,
                response_deserializer=ghost__pb2.HealthResponse.FromString,
                _registered_method=True)


class GhostPipelineServicer:
    """Ghost IT Agent → Pipeline Server communication
    All connections: mTLS required

    """

    def IngestEvents(self, request_iterator, context):
        """Stream events from agent to pipeline
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GhostPipelineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestEvents,
                    request_deserializer=ghost__pb2.EventBatch.FromString,
                    response_serializer=ghost__pb2.IngestResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ghost__pb2.HealthRequest.FromString,
                    response_serializer=ghost__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ghost.GhostPipeline', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ghost.GhostPipeline', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GhostPipeline:
    """Ghost IT Agent → Pipeline Server communication
    All connections: mTLS required

    """

    @staticmethod
    def IngestEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ghost.GhostPipeline/IngestEvents',
            ghost__pb2.EventBatch.SerializeToString,
            ghost__pb2.IngestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.GhostPipeline/HealthCheck',
            ghost__pb2.HealthRequest.SerializeToString,
            ghost__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
