# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ghost.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ghost.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bghost.proto\x12\x05ghost\"\xdc\x01\n\x05\x45vent\x12\n\n\x02ts\x18\x01 \x01(\x04\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x0c\n\x04tgid\x18\x03 \x01(\r\x12\x12\n\nparent_pid\x18\x04 \x01(\x04\x12\x0b\n\x03uid\x18\x05 \x01(\r\x12\x0b\n\x03gid\x18\x06 \x01(\r\x12\x0c\n\x04\x63omm\x18\x07 \x01(\t\x12\x12\n\nevent_type\x18\x08 \x01(\t\x12\x10\n\x08priority\x18\t \x01(\r\x12\r\n\x05\x66lags\x18\n \x01(\r\x12\x0c\n\x04path\x18\x0b \x01(\t\x12\r\n\x05score\x18\x0c \x01(\x02\x12\r\n\x05\x61lert\x18\r \x01(\x08\x12\x0f\n\x07reasons\x18\x0e \x03(\t\"e\n\nEventBatch\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x15\n\ragent_version\x18\x02 \x01(\t\x12\x1c\n\x06\x65vents\x18\x03 \x03(\x0b\x32\x0c.ghost.Event\x12\x10\n\x08\x62\x61tch_ts\x18\x04 \x01(\x04\"K\n\x0eIngestResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x17\n\x0f\x65vents_received\x18\x02 \x01(\r\x12\x0f\n\x07message\x18\x03 \x01(\t\"!\n\rHealthRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"L\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x16\n\x0eserver_version\x18\x02 \x01(\t\x12\x11\n\tserver_ts\x18\x03 \x01(\x04\x32\x87\x01\n\rGhostPipeline\x12:\n\x0cIngestEvents\x12\x11.ghost.EventBatch\x1a\x15.ghost.IngestResponse(\x01\x12:\n\x0bHealthCheck\x12\x14.ghost.HealthRequest\x1a\x15.ghost.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ghost_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=23
  _globals['_EVENT']._serialized_end=243
  _globals['_EVENTBATCH']._serialized_start=245
  _globals['_EVENTBATCH']._serialized_end=346
  _globals['_INGESTRESPONSE']._serialized_start=348
  _globals['_INGESTRESPONSE']._serialized_end=423
  _globals['_HEALTHREQUEST']._serialized_start=425
  _globals['_HEALTHREQUEST']._serialized_end=458
  _globals['_HEALTHRESPONSE']._serialized_start=460
  _globals['_HEALTHRESPONSE']._serialized_end=536
  _globals['_GHOSTPIPELINE']._serialized_start=539
  _globals['_GHOSTPIPELINE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
